### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by besheagl** [besheagl/UNCG-Senior-Project#13]
User story: as a user, I want a profile page, so that I can show off my profile picture and interests.

Create HTML layout.
Use CSS to clean it up.

**Comment by besheagl** [comment]
@ekwells Became a little unsure when I was trying to work out what the interface would look like for adding a show/book to a list. I'd welcome suggestions!

**Comment by ekwells** [comment]
Maybe have a +Add button next to each list? or above each list? are they are displayed horizontally or vertically? And then after pushing the add button, maybe it will be a popup with a search bar? Or maybe the search bar can be on another screen?

**Comment by besheagl** [comment]
Yeah, I think the + button is a good idea. I have them displaying vertically at the moment. I think the search bar on another screen would be a good idea, I'll have to play around with it. I'm not sure I'll get the Feed and Show pages done by tomorrow's class but Imma try real hard ^^'
